### Signup User and generate and set session token
POST https://localhost:4000/api/user/signup
Content-Type: application/json

{
"email": "TheTestingLecturer@gmail.com",
"password": "test_password",
"username": "Le_Tester"
}

### Login User and generate and set session token

POST https://localhost:4000/api/user/login
Content-Type: application/json

{
"email": "TheLecturerTest@gmail.com",
"password": "test_password"
}

### Home Page (Check Cookie token --> User Logged in?)

POST https://localhost:4000/api/user/
Content-Type: application/json

{
}

### Logout User (Check that user is logged out, by running the previous test)

GET https://localhost:4000/api/user/logout
Content-Type: application/json

{
}

###Post Page (Get All Posts)

GET  https://localhost:4000/api/posts/
Content-Type: application/json

{
}

### Create a new post (You must be logged in first)

POST https://localhost:4000/api/posts/
Content-Type: application/json

{
"caption": "Test Post 8"
}

### Delete a post (By id) format -> url/{Post ID} (You must be logged in first)

DELETE  https://localhost:4000/api/posts/652408897bf14db6296b1f45

{

}